version: "3.3"
networks:
  lnnet:

services:
  bitcoind:
    container_name: bitcoind
    build:
        context: bitcoind
    image: lnbook/bitcoind:latest
    networks:
      - lnnet
    expose:
      - "18443"
      - "12005"
      - "12006"
    restart: always

  Alice:
    container_name: Alice
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Bob:
    container_name: Bob
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Carol:
    container_name: Carol
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Dave:
    container_name: Dave
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Ema:
    container_name: Ema
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Frank:
    container_name: Frank
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always

  Geny:
    container_name: Geny
    build:
        context: lnd
    image: lnbook/lnd:latest
    networks:
      - lnnet
    expose:
      - "9735"
    restart: always
